--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06/07/2015 11:14:27 p.m.
-- Server version: 5.6.14
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE sysvacunacion;

--
-- Definition for table tblcorreos
--
DROP TABLE IF EXISTS tblcorreos;
CREATE TABLE tblcorreos (
  IdCorreo INT(11) NOT NULL AUTO_INCREMENT,
  Correos VARCHAR(35) NOT NULL,
  CedulaUsuario INT(15) NOT NULL,
  PRIMARY KEY (IdCorreo),
  INDEX FK_tblcorreos_tblusuarios_IdCliente (CedulaUsuario)
)
ENGINE = INNODB
AUTO_INCREMENT = 27
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Definition for table tblusuarios
--
DROP TABLE IF EXISTS tblusuarios;
CREATE TABLE tblusuarios (
  IdUsuario INT(11) NOT NULL AUTO_INCREMENT,
  Cedula INT(15) NOT NULL,
  Nombre VARCHAR(15) DEFAULT NULL,
  Apellidos VARCHAR(15) DEFAULT NULL,
  Usuario VARCHAR(15) DEFAULT NULL,
  Contrasenia VARCHAR(25) DEFAULT NULL,
  Direccion VARCHAR(60) DEFAULT NULL,
  FechaNacimiento DATE DEFAULT NULL,
  Activo INT(2) DEFAULT NULL,
  Rol VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (IdUsuario),
  UNIQUE INDEX Cedula (Cedula)
)
ENGINE = INNODB
AUTO_INCREMENT = 88776876
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Definition for table tblvacunasporcitas
--
DROP TABLE IF EXISTS tblvacunasporcitas;
CREATE TABLE tblvacunasporcitas (
  Id INT(4) DEFAULT NULL,
  UNIQUE INDEX UK_tblvacunasporcitas_Id (Id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Definition for table tblcitas
--
DROP TABLE IF EXISTS tblcitas;
CREATE TABLE tblcitas (
  Id INT(11) NOT NULL,
  IdVacunador INT(11) DEFAULT NULL,
  Fecha VARCHAR(30) DEFAULT NULL,
  Vacunas INT(11) DEFAULT NULL,
  IdCliente INT(11) DEFAULT NULL,
  Direccion VARCHAR(30) DEFAULT NULL,
  Dosis VARCHAR(15) DEFAULT NULL,
  Completada INT(5) DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX FK_tblcitas_tbladministrador_Id (IdVacunador),
  INDEX FK_tblcitas_tblvacunas_Id (Vacunas),
  CONSTRAINT FK_tblcitas_tblusuarios_Id FOREIGN KEY (IdCliente)
    REFERENCES tblusuarios(IdUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_tblcitas_tblvacunasporcitas_Id FOREIGN KEY (Id)
    REFERENCES tblvacunasporcitas(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Definition for table tblpadecimientos
--
DROP TABLE IF EXISTS tblpadecimientos;
CREATE TABLE tblpadecimientos (
  Cedula INT(15) DEFAULT NULL,
  Padecimientos VARCHAR(20) DEFAULT NULL,
  Id INT(11) NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_tblpadecimientos_tblusuarios_Id FOREIGN KEY (Cedula)
    REFERENCES tblusuarios(IdUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Definition for table tbltelefonos
--
DROP TABLE IF EXISTS tbltelefonos;
CREATE TABLE tbltelefonos (
  IdTelefono INT(11) NOT NULL AUTO_INCREMENT,
  Telefono INT(11) DEFAULT NULL,
  CedulaUsuario INT(15) DEFAULT NULL,
  PRIMARY KEY (IdTelefono),
  CONSTRAINT FK_tbltelefonos_tblusuarios_Cedula FOREIGN KEY (CedulaUsuario)
    REFERENCES tblusuarios(Cedula) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tblvacunas
--
DROP TABLE IF EXISTS tblvacunas;
CREATE TABLE tblvacunas (
  IdVacunas INT(3) NOT NULL AUTO_INCREMENT,
  NombreVacuna VARCHAR(15) DEFAULT NULL,
  DescripcionVacuna VARCHAR(30) DEFAULT NULL,
  TipoVacuna VARCHAR(15) DEFAULT NULL,
  ActivoVacuna INT(5) DEFAULT NULL,
  PRIMARY KEY (IdVacunas),
  CONSTRAINT FK_tblvacunas_tblvacunasporcitas_Id FOREIGN KEY (IdVacunas)
    REFERENCES tblvacunasporcitas(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

DELIMITER $$

--
-- Definition for procedure existeUsuario
--
DROP PROCEDURE IF EXISTS existeUsuario$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE existeUsuario(IN pUser VARCHAR(30))
BEGIN
  
  SELECT Usuario FROM tblusuarios WHERE Usuario = pUser;

END
$$

--
-- Definition for procedure guardarUsuario
--
DROP PROCEDURE IF EXISTS guardarUsuario$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE guardarUsuario(IN pCedula INT(15), IN pNombre VARCHAR(15), IN pApellidos VARCHAR(15), IN pUsuario VARCHAR(15), IN pContrasenia VARCHAR(25), IN pDireccion VARCHAR(60), IN pFechaNacimiento VARCHAR(20), IN pCorreos VARCHAR(30), IN pActivo INT, IN pRol VARCHAR(15), IN pTelefono INT, IN pIdUsuario INT, IN pIdCorreo INT, IN pIdTelefono INT)
BEGIN

  insert into tblusuarios values(pIdUsuario,pCedula,pNombre,pApellidos,pUsuario,pContrasenia,pDireccion,STR_TO_DATE(pFechaNacimiento, '%d/%m/%YYYY'),pActivo,pRol);

 insert into tblcorreos VALUES(pIdCorreo,pCorreos,pCedula);
  insert into tbltelefonos VALUES(pIdTelefono,pTelefono,pCedula);

END
$$

--
-- Definition for procedure verificarLogin
--
DROP PROCEDURE IF EXISTS verificarLogin$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE verificarLogin(IN pUser VARCHAR(15), IN pPass VARCHAR(15))
BEGIN
    SELECT * from tblusuarios, tblcorreos, tbltelefonos
      WHERE Usuario = pUser and Contrasenia = pPass and tblusuarios.Cedula LIKE tblcorreos.CedulaUsuario AND tblusuarios.Cedula LIKE tbltelefonos.CedulaUsuario;

END
$$

DELIMITER ;

-- 
-- Dumping data for table tblcorreos
--
INSERT INTO tblcorreos VALUES
(24, 'fula@gmail.com', 12345678),
(25, 'luisibaja263@gmail.com', 116010394),
(26, 'giova@hotmail.com', 1234123);

-- 
-- Dumping data for table tblusuarios
--
INSERT INTO tblusuarios VALUES
(1, 12345678, 'Fulano', 'Menganito', 'fula', 'fula', 'Masaya', '2010-09-09', 1, 'cliente'),
(2, 116010394, 'Luis Antonio', 'Sibaja Cantilla', 'luisibaja3', 'admin', 'Nuevo Arenal, Tilarán', '1995-03-26', 1, 'administrador'),
(3, 1234123, 'Giova', 'Jimenes', 'giova', 'giova', 'Heredia', '1997-01-26', 1, 'cliente');

-- 
-- Dumping data for table tblvacunasporcitas
--

-- Table sysvacunacion.tblvacunasporcitas does not contain any data (it is empty)

-- 
-- Dumping data for table tblcitas
--

-- Table sysvacunacion.tblcitas does not contain any data (it is empty)

-- 
-- Dumping data for table tblpadecimientos
--

-- Table sysvacunacion.tblpadecimientos does not contain any data (it is empty)

-- 
-- Dumping data for table tbltelefonos
--
INSERT INTO tbltelefonos VALUES
(2, 88888888, 12345678),
(3, 84946873, 116010394),
(4, 88776868, 1234123);

-- 
-- Dumping data for table tblvacunas
--

-- Table sysvacunacion.tblvacunas does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;